apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sc-nginx
  name: sc-nfs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-nginx
  template:
    metadata:
      labels:
        app: sc-nginx
    spec:
      volumes:
        - name: nfs-nginx
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - image: harbor.lab.local/ezmeral/nginx:latest
          name: nginx
          volumeMounts:
            - name: nfs-nginx
              mountPath: /usr/share/nginx/html


---

apiVersion: v1
kind: Service
metadata:
  name: sc-nfs-nginx
  labels:
    app: sc-nginx
spec:
  type: NodePort
  selector:
    app: sc-nginx
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30183
